apiVersion: v1
data:
  MYSQL_PASSWORD: YWRtaW4=
  MYSQL_ROOT_PASSWORD: YWRtaW4=
  MYSQL_USER: cm9vdA==
kind: Secret
metadata:
  creationTimestamp: "2026-07-31T10:30:33Z"
  name: mysql-secret
  namespace: default
  resourceVersion: "10372"
  uid: 76dfe17f-64a8-4ee4-8f28-7271f75ffc47
type: Opaque
